default_stages: [pre-commit]
repos:
  # Stage 1: Code quality checks - these run only on staged files
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        stages: [pre-commit]
        exclude: ^ai-docs/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
        args: [--fix, --config=.config/ruff.toml]
        stages: [pre-commit]
        exclude: ^ai-docs/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --config-file=.config/mypy.ini]
        stages: [pre-commit]
        exclude: ^ai-docs/

  # Stage 2: Documentation generation - runs only after all other hooks pass
