# Basic Ruff configuration
target-version = "py311"
line-length = 100

[lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "N",   # pep8-naming
    "W",   # pycodestyle warnings
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "SIM", # flake8-simplify
    "UP",  # pyupgrade
]
ignore = [
    "F821", # Ignore undefined names in template strings
    "E501", # Line too long (handled by black)
]

# Path-specific settings
[lint.per-file-ignores]
"src/create_python_project/utils/templates.py" = ["E501", "F821"]
"tests/*" = ["E501"]
